### ISSUE TITLE
这个strip('"\'')的作用是什么呢?

### ISSUE THREAD

**Issue by misakar** [mozillazg/lsbate#4]
你好, 请问这行代码 : https://github.com/mozillazg/lsbate/blob/master/part4/template4c.py#L160
strip('"\'')的作用是什么呢？

**Comment by misakar** [comment]
呃，我明白了... 去除文件名称的" 或者 '
感谢你的文章!

**Comment by mozillazg** [comment]
@neo1218 不客气 😆

**Comment by misakar** [comment]
@mozillazg  昨天看到了一个pycon视频: [Code Generation in Python: Dismantling Jinja
](https://www.youtube.com/watch?v=jXlR0Icvvh8) 演讲者是JInja的作者@mitsuhiko. 说到了Jinja的模版解析过程,  是你在文章最后提到的“使用词法分析/语法分析的方式来解析模板内容”， 可以参考一下. 我昨天看了一遍好多地方还没看明白... Jinja作者的英语口音好奇怪...

**Comment by mozillazg** [comment]
@neo1218 感谢分享。我会抽空看一下的。
